### PR TITLE
fix compilation error with solc > 0.8, fixes #177

### LINKED ISSUE #177: Incorrect version pragma for PoolAddress
Compiling [PoolAddress](https://github.com/Uniswap/uniswap-v3-periphery/blob/main/contracts/libraries/PoolAddress.sol) with solc v0.8.1 gives the following error:
```sh
TypeError: Explicit type conversion not allowed from "uint256" to "address".
  --> @uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:35:16:
   |
35 |         pool = address(
   |                ^ (Relevant source part starts here and spans across multiple lines).
```
With solc >= 0.8.0 intermediate casts have to be performed to get from uint256 to address. [docs.soliditylang.org](https://docs.soliditylang.org/en/breaking/080-breaking-changes.html#new-restrictions)
Fix by setting pragma to `pragma solidity >=0.5.0 < 0.8.0`.

### LINKED ISSUE #209: PoolAddress library is giving an error in Solidity 0.8+
Dear Uniswap team,

I've been using the PoolAddress library in smart contracts, to get the address of a pool with the tokens and fee, and it seems like a recent update in solidity (0.8) has broken the way that the address is computed. 

`TypeError: Explicit type conversion not allowed from "uint256" to "address".
  --> @uniswap/v3-periphery/contracts/libraries/PoolAddress.sol:35:16:
   |
35 |         pool = address(
   |                ^ (Relevant source part starts here and spans across multiple lines).`

As you can see, a uint256 cannot be casted to address directly. As a workaround I have casted the uint256 to uint160 first, which works. Obviously, modifying the underlying source code in node_modules is not a practical solution. Should I do a PR with the right fixes on the file?

Kind regards,
deAngelisAlex

### PR DESCRIPTION
**Pull request by ChrisiPK**
Fixes the compilation error in PoolLibrary with Solidity 0.8. Now, we first cast to uin160 before casting to address.

### CODE REVIEW

**Comment by ChrisiPK** [comment]
> Thanks for this change, could you move this to a separate branch called '0.8', similar to what we did for v3-core [here](https://github.com/Uniswap/v3-core/compare/main...0.8)?

I will try to update all the contract to 0.8 and create a second PR for this.

However, I disagree that this change should not be incorporated into the 0.7 version. It doesn't break compatibility with older versions and enables users to include the `PoolAddress` contract in their 0.8 projects already. The solidity version pragma of this file doesn't exclude compatibility with 0.8 so it should be fixed to work with 0.8.

**Comment by ChrisiPK** [comment]
> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

Still relevant IMHO. Would be happy to hear from maintainers what is blocking it from their perspective.

**Comment by therealdannzor** [comment]
> 

Curious to know too 😄

**Comment by cruzdanilo** [comment]
still relevant

**Comment by jmfrancolin** [comment]
still relevant

**Comment by A-ndy-git** [comment]
+1

**Comment by ethanolle** [comment]
+1

**Review by ethanolle — APPROVED** [review]
Working great tested locally

**Comment by andreujuanc** [comment]
Can anyone check if the truncation is done right? and behaves according to < v8?

**Comment by cruzdanilo** [comment]
still relevant

**Review by Polobandit23 — APPROVED** [review]

**Comment by ChrisiPK** [comment]
Still relevant. I would also like to know if there is anything blocking it and if there is something we can do to move it forward.

@andreujuanc How do you suggest to test this?

**Comment by andreujuanc** [comment]
@ChrisiPK Sadly I don't remember why I was checking this PR :D

**Comment by passabilities** [comment]
any updates?

**Comment by kryptoklob** [comment]
still relevant

**Comment by arr00** [comment]
This should be merged @hensha256
